### ISSUE TITLE
Synchronisation fails when name contains emoji

### ISSUE THREAD

**Issue by eperrotta** [oroinc/OroCRMZendeskBundle#2]
Hello guys,
the synchronization via API with zendesk fails when the name of the user contains emoji.

<img width="490" alt="screen shot 2017-06-29 at 12 08 55" src="https://user-images.githubusercontent.com/5153895/27682752-02f4c9c6-5cc4-11e7-9a45-30ba111e421a.png">

`app.ERROR: An exception occurred while executing 'INSERT INTO orocrm_zd_user (origin_id, url, external_id, name, details, ticket_restrictions, only_private_comments, notes, verified, active, alias, email, phone, time_zone, locale, last_login_at, created_at, updated_at, origin_created_at, origin_updated_at, role_name, related_contact_id, related_user_id, channel_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [8492528725, "https:\/\/clientaccount.zendesk.com\/api\/v2\/users\/8492528725.json", null, "\ud83d\udc96Ute Hillebrand", null, "requested", 0, null, 0, 1, null, "censoredmail@domain.tld", null, "Paris", "de", null, "2017-06-29 10:06:26", "2017-06-29 10:06:26", "2016-12-22 06:38:20", "2016-12-22 06:38:20", "end-user", 23097, null, 4]:  SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x92\x96Ut...' for column 'name' at row 1 [] []`

I already tried to change the `name` field encoding and collation to utf8mb4 utf8mb4_general_ci but this doesn't solve the issue.

Any hint?

Thanks

**Comment by mymias** [comment]
Hello, @eperrotta!

What version of MySQL server are you using?

**Comment by eperrotta** [comment]
I am using Mysql 5.7.
To fix the issue I had to:
1. Change the encoding/collation of the fields
2. Adding this configuration to the app/config/config.yml file
doctrine:
`    dbal:`
`        charset: utf8mb4`
`        default_table_options:`
`            charset: utf8mb4`
`            collate: utf8mb4_unicode_ci`

**Comment by mymias** [comment]
@eperrotta , thanks a lot for providing the solution.
Probably we'll update the OroPlatform installation documentation with this information.

Best regards.
